### ISSUE TITLE
gaussian parser: Wrong number of basis functions

### ISSUE THREAD

**Issue by BalticPinguin** [cclib/cclib#1048]
Hi,
I am not very deep into the topic and didn't find time for detailed analysis; but I have a rather recent g16-file that doesn't parse properly:
I simply run
````   
    init_file=argv[0]
    ini_kwargs = dict()
    data_ini=file_ini.parse()
````
For some reason, here some "NBasis =  52"-keywords show up, overriding the initially correct `self.nbasis = 42`-value and thus the reading of mo-coefficients fail...

[initial.log.txt](https://github.com/cclib/cclib/files/6697243/initial.log.txt)

I hope this is good information for a fix; and someone can work through this...

Best regards

**Comment by BalticPinguin** [comment]
Hm... At least the easy workaround is to remove the 'opt(Verytight)' from the input-file; (which is pointless in atoms). Than, the spurious sections don't appear.

For me, it looks like a bug in g16? But still, one should be able to cope with it, I guess...

**Comment by berquist** [comment]
```
$ ccget --list 1048.log
Attempting to read 1048.log
[Gaussian 1048.log ERROR] Encountered error when parsing.
[Gaussian 1048.log ERROR] Last line read:                            6         7         8         9        10

Traceback (most recent call last):
  File "/home/eric/.pyenv/versions/miniconda3-4.7.12/envs/cclib_berquist_37/bin/ccget", line 33, in <module>
    sys.exit(load_entry_point('cclib', 'console_scripts', 'ccget')())
  File "/home/eric/development/cclib_berquist/cclib/scripts/ccget.py", line 176, in ccget
    data = ccread(filename, **kwargs)
  File "/home/eric/development/cclib_berquist/cclib/io/ccio.py", line 169, in ccread
    return log.parse()
  File "/home/eric/development/cclib_berquist/cclib/parser/logfileparser.py", line 315, in parse
    self.extract(inputfile, line)
  File "/home/eric/development/cclib_berquist/cclib/parser/gaussianparser.py", line 1714, in extract
    mocoeffs[0][base:base + len(part) // 10, i] = temp
ValueError: could not broadcast input array from shape (5,) into shape (4,)
```
It looks like different parts of the calculation are done with Cartesian instead of pure basis functions, because that's where those numbers come from:
```
45 basis functions,   102 primitive gaussians,    52 cartesian basis functions
```

**Comment by langner** [comment]
That is rather odd. @berquist do you think we should at least not fail parsing in this case (and add as a regression)?
