### ISSUE TITLE
ORCA NEB calculation

### ISSUE THREAD

**Issue by andre-cloud** [cclib/cclib#1113]
Is there a method that help you tracking the NEB calculation submitted with orca?

**Comment by berquist** [comment]
Hi Andrea, is there anything in particular you wanted to extract?

I did try parsing an example and get an error, but I'm not sure if it's because the TS optimization following the NEB steps didn't converge within the maximum number of cycles.  If you have an example of an output you'd like to parse, can you share it as an attachment?
```
Attempting to read example.out
[ORCA example.out ERROR] Encountered error when parsing.
[ORCA example.out ERROR] Last line read:           ........................................................

Traceback (most recent call last):
  File "/home/eric/.pyenv/versions/miniconda3-4.7.12/envs/cclib_berquist_37/bin/ccget", line 33, in <module>
    sys.exit(load_entry_point('cclib', 'console_scripts', 'ccget')())
  File "/home/eric/development/cclib_berquist/cclib/scripts/ccget.py", line 176, in ccget
    data = ccread(filename, **kwargs)
  File "/home/eric/development/cclib_berquist/cclib/io/ccio.py", line 172, in ccread
    return log.parse()
  File "/home/eric/development/cclib_berquist/cclib/parser/logfileparser.py", line 315, in parse
    self.extract(inputfile, line)
  File "/home/eric/development/cclib_berquist/cclib/parser/orcaparser.py", line 703, in extract
    for i, n in enumerate(self.geotargets_names):
AttributeError: 'ORCA' object has no attribute 'geotargets_names'
```
[example.out.txt](https://github.com/cclib/cclib/files/8238451/example.out.txt)

**Comment by andre-cloud** [comment]
When it will converge in the assigned optimization cycles, I will surely share with the community

**Comment by andre-cloud** [comment]
Hi
I've finnaly found the time to spend some time on NEB calculations, and I managed to get the convergency I was hoping for. 

I attach the zip folder of the whole calculation, and an example of a graph extracted from ```neb.interp``` file as well the python script that I use to extract that kind of data from this latter file.
 
[cho_nh2.zip](https://github.com/cclib/cclib/files/9539905/cho_nh2.zip)
![neb](https://user-images.githubusercontent.com/55535285/189476711-4afc4203-fc2b-4ae6-bacc-d2e944a26076.png)

```python 

import matplotlib.pyplot as plt 
import numpy as np
import argparse, sys

parser = argparse.ArgumentParser()
parser.add_argument('filename', help='The interpolation file generated by ORCA', default='neb.interp', nargs='+')
parser.add_argument('-s', '--silent', help='Flag if you want to only see the graph generated without saving it', action='store_true')
parser.add_argument('-o', '--output', help='Output filename for the graph')


args = parser.parse_args()

H = 627.5096080305927


def parse_file(filename):
    with open(filename) as f:
        file = f.read()

    iters = file.split('Iteration')[1:]
    imags, interpols = [] , []
    for i in iters:
        if not i: continue
        imag, interp, *_ = i.split('''

''')
        img = np.array( [i.split() for i in imag.split('\n')[2:]])
        x, _ , y = img[:, 0], img[:, 1], img[:, 2]
        imags.append(np.array([(float(i), float(j)*H) for i, j in zip(x,y)]))
        intr = np.array( [i.split() for i in interp.split('\n')[2:] if i])
        x, _ , y = intr[:, 0], intr[:, 1], intr[:, 2]
        interpols.append(np.array([(float(i), float(j)*H) for i, j in zip(x,y)]))
    
    return imags, interpols



for file in args.filename:

    imags, interpols = parse_file(file)

    for idx, i in enumerate(interpols):
        x, y = i[:, 0], i[:, 1]
        c = 'gray' if (idx != 0 and idx != len(interpols)-1) else 'black' if idx == 0 else 'red'
        alpha = 0.1 if (idx != 0 and idx != len(interpols)-1) else 0.8 if idx == 0 else 1
        w = 0.2 if (idx != 0 and idx != len(interpols)-1) else 0.8 if idx == 0 else 1
        plt.plot(x, y, color=c, alpha=alpha, linewidth=w)
        
    for idx, i in enumerate(imags):
        x, y = i[:, 0], i[:, 1]
        c = 'gray' if (idx != 0 and idx != len(imags)-1) else 'black' if idx == 0 else 'red'
        alpha = 0.15 if (idx != 0 and idx != len(imags)-1) else 0.8 if idx == 0 else 1
        s = 20 if (idx != 0 and idx != len(interpols)-1) else 30 if idx == 0 else 35
        plt.scatter(x, y, color=c, alpha=alpha, s=s)


    plt.title(f'NEB Analysis - {len(imags)} iterations')
    plt.xlabel('Reaction coordinate')
    plt.ylabel('∆E [kcal/mol]')

    plt.xlim((0, 1))

    plt.tight_layout()
    if args.silent:
        plt.show()
    else:
        plt.savefig(f'{file.split(".")[0]}.png', dpi=300)

```
