### ISSUE TITLE
Problems with documentation

### ISSUE THREAD

**Issue by langner** [cclib/cclib#1154]
Something wrong with documentation
- On verison 1.7 currently - not being published to GH pages?
- Coverage table not working on readthedocs (new generated version)

**Comment by shivupa** [comment]
Docs build failed on #1157

**Comment by berquist** [comment]
GH pages are being served from https://github.com/cclib/cclib.github.io which we must have been updating manually. It's disabled from the main repository:
![Screenshot from 2023-03-08 12-24-56](https://user-images.githubusercontent.com/727571/223785448-3a3bc555-13c6-4714-8563-febf2f2f049c.png)
Ideally the RTD build result gets pushed to cclib.github.io rather than needing to rebuild it, which I think is the only option from the settings interface?

**Comment by berquist** [comment]
Reminder: when looking at this, also fix the last part of #997.

**Comment by berquist** [comment]
#709 might still be problem here, not sure if it's related to the tables not showing.

**Comment by berquist** [comment]
Now RTD is broken (https://readthedocs.org/projects/cclib/builds/20580416/).  Maybe it's as simple as switching from Python 3.7 to 3.10 in `.readthedocs.yml`.
```
 Running Sphinx v5.3.0

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cclib/envs/1200/lib/python3.7/site-packages/sphinx/registry.py", line 459, in load_extension
    mod = import_module(extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cclib/envs/1200/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/cclib/envs/1200/lib/python3.7/site-packages/sphinx/builders/linkcheck.py", line 18, in <module>
    from requests import Response
  File "/home/docs/checkouts/readthedocs.org/user_builds/cclib/envs/1200/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/docs/checkouts/readthedocs.org/user_builds/cclib/envs/1200/lib/python3.7/site-packages/urllib3/__init__.py", line 39, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cclib/envs/1200/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    args.pdb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cclib/envs/1200/lib/python3.7/site-packages/sphinx/application.py", line 219, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cclib/envs/1200/lib/python3.7/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cclib/envs/1200/lib/python3.7/site-packages/sphinx/registry.py", line 463, in load_extension
    err) from err
sphinx.errors.ExtensionError: Could not import extension sphinx.builders.linkcheck (exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168)

Extension error:
Could not import extension sphinx.builders.linkcheck (exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168)
```

**Comment by berquist** [comment]
#1216 merged but it deploys to https://cclib.github.io/cclib and not http://cclib.github.io/.

**Comment by berquist** [comment]
#1223 attempts to push to cclib.github.io via https://github.com/cclib/cclib.github.io but there is a problem with the CI runner.

**Comment by berquist** [comment]
#1227 fixed the problem with the CI runner.

Now it looks like there are problems with bulleted lists in Sphinx.

**Comment by shivupa** [comment]
> Now it looks like there are problems with bulleted lists in Sphinx.

Am I just missing this? Can you link to where its breaking?

**Comment by berquist** [comment]
Nope, looks ok now.  Must have been a browser thing on my end.

What do we do about the fact that there is both http://cclib.github.io (yes, not https) and https://cclib.github.io/cclib?

**Comment by shivupa** [comment]
Unpublished the second and forced https on the first. I didn't want to unpublish until everything seemed resolved, but it seems like we are good

**Comment by berquist** [comment]
Done! Thank you for doing all of this.
