### ISSUE TITLE
ccread/ccget support for cjson is not working

### ISSUE THREAD

**Issue by oliver-s-lee** [cclib/cclib#1234]
`ccread` (and by extension the `ccget` script) cannot currently read from cjson:

```
# To generate the cjson file.
> ccwrite cjson dvb_gopt.out.zip
> ccget --json dvb_gopt.out.cjson metadata
Attempting to read dvb_gopt.out.cjson
Traceback (most recent call last):
  File "/home/oliver/.local/bin/ccget", line 8, in <module>
    sys.exit(ccget())
  File "/home/oliver/dev/cclib/cclib Src/cclib/scripts/ccget.py", line 179, in ccget
    data = ccread(filename, **kwargs)
  File "/home/oliver/dev/cclib/cclib Src/cclib/io/ccio.py", line 158, in ccread
    return log.read_cjson()
AttributeError: 'CJSON' object has no attribute 'read_cjson'
```
Indeed the CJSON reader does not support a `read_cjson()` method. This should be `parse()` instead like other parsers, but ccread goes out of its way to call `read_cjson()` if the input is flagged as csjon, so presumably this was part of the interface in the past.

This issue is separate to, but will be fixed by, #1222

**Comment by oliver-s-lee** [comment]
This is missed in the tests because `CJSONReaderTest.test_cjson_read()` calls `CJSON.parse()` directly rather than using the ccread interface (which it probably should).
