### ISSUE TITLE
Gaussian ONIOM parsing problems and potentially new attributes

### ISSUE THREAD

**Issue by oliver-s-lee** [cclib/cclib#1272]
Thanks to @jvalegre for proving the attached file which fails to parse with the following:

[TS.log.log.zip](https://github.com/cclib/cclib/files/12506050/TS.log.log.zip)

```
Attempting to read TS.log.log
[Gaussian TS.log.log ERROR] Encountered error when parsing.
[Gaussian TS.log.log ERROR] Last line read:                       A                      A                      A

Traceback (most recent call last):
  File "/home/oliver/.local/bin/ccget", line 8, in <module>
    sys.exit(ccget())
  File "/home/oliver/dev/cclib/cclib Src/cclib/scripts/ccget.py", line 188, in ccget
    data = ccread(filename, **kwargs)
  File "/home/oliver/dev/cclib/cclib Src/cclib/io/ccio.py", line 190, in ccread
    return log.parse()
  File "/home/oliver/dev/cclib/cclib Src/cclib/parser/logfileparser.py", line 171, in parse
    self.extract(self.inputfile, line)
  File "/home/oliver/dev/cclib/cclib Src/cclib/parser/gaussianparser.py", line 1490, in extract
    numbers = [float(s) for s in line[10:].split()]
  File "/home/oliver/dev/cclib/cclib Src/cclib/parser/gaussianparser.py", line 1490, in <listcomp>
    numbers = [float(s) for s in line[10:].split()]
ValueError: could not convert string to float: 'A'
```

Once the parsing bug is fixed, there may also be new properties we're interested in parsing (will confirm with @jvalegre once bug fixed)

**Comment by oliver-s-lee** [comment]
This is the same error as in https://github.com/cclib/cclib/pull/1286
