### ISSUE TITLE
versioningit version too much restrictive

### ISSUE THREAD

**Issue by sagitter** [cclib/cclib#1444]
Hi all.

I need to recompile `python-cclib-1.8.1` in Fedora 40+ with `versioningit-3.1.1`. Can it be done?

**Comment by berquist** [comment]
Hi Antonio, I think I've tried removing the version restriction and it worked.  I don't recall any  problems.  Try patching this in a copy of the source code.

**Comment by sagitter** [comment]
I forget to say that i'm using Python-3.12 in Fedora 40.
I simply removed the `versioningit`'s version minimal request from [pyproject.toml](https://github.com/cclib/cclib/blob/07260dd0394cb1a2381d4d897746d727a12ad6ce/pyproject.toml#L67)

```
+ CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld-errors -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1  '
+ TMPDIR=/home/sagitter/rpmbuild/BUILD/cclib-1.8.1/.pyproject-builddir
+ RPM_TOXENV=py312
+ HOSTNAME=rpmbuild
+ /usr/bin/python3 -Bs /usr/lib/rpm/redhat/pyproject_buildrequires.py --generate-extras --python3_pkgversion 3 --wheeldir /home/sagitter/rpmbuild/BUILD/cclib-1.8.1/pyproject-wheeldir --output /home/sagitter/rpmbuild/BUILD/python-cclib-1.8.1-1.fc40.x86_64-pyproject-buildrequires -x tests
Handling setuptools >= 61.0 from build-system.requires
Requirement satisfied: setuptools >= 61.0
   (installed: setuptools 69.0.3)
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/versioningit/git.py", line 152, in ensure_is_repo
    self.read(
  File "/usr/lib/python3.12/site-packages/versioningit/git.py", line 184, in read
    return readcmd("git", *args, cwd=str(self.path), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/versioningit/util.py", line 71, in readcmd
    s = runcmd(*args, stdout=subprocess.PIPE, text=True, **kwargs).stdout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/versioningit/util.py", line 66, in runcmd
    return subprocess.run(arglist, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--is-inside-work-tree']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/versioningit/core.py", line 260, in run
    description = self.do_vcs()
                  ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/versioningit/core.py", line 324, in do_vcs
    description = self.vcs(project_dir=self.project_dir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/versioningit/methods.py", line 162, in __call__
    return self.method(params=self.params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/versioningit/git.py", line 229, in describe_git
    repo.ensure_is_repo()
  File "/usr/lib/python3.12/site-packages/versioningit/git.py", line 162, in ensure_is_repo
    raise NotVCSError(f"{self.path} is not in a Git repository")
versioningit.errors.NotVCSError: /home/sagitter/rpmbuild/BUILD/cclib-1.8.1 is not in a Git repository

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/versioningit/core.py", line 548, in get_version_from_pkg_info
    Path(project_dir, "PKG-INFO").read_text(encoding="utf-8")
  File "/usr/lib64/python3.12/pathlib.py", line 1027, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/sagitter/rpmbuild/BUILD/cclib-1.8.1/PKG-INFO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/versioningit/hook.py", line 23, in setuptools_finalizer
    report = vgit.run(write=True, fallback=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/versioningit/core.py", line 283, in run
    version=get_version_from_pkg_info(self.project_dir)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/versioningit/core.py", line 551, in get_version_from_pkg_info
    raise NotSdistError(f"{project_dir} does not contain a PKG-INFO file")
versioningit.errors.NotSdistError: /home/sagitter/rpmbuild/BUILD/cclib-1.8.1 does not contain a PKG-INFO file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/rpm/redhat/pyproject_buildrequires.py", line 560, in main
    generate_requires(
  File "/usr/lib/rpm/redhat/pyproject_buildrequires.py", line 456, in generate_requires
    generate_build_requirements(backend, requirements)
  File "/usr/lib/rpm/redhat/pyproject_buildrequires.py", line 274, in generate_build_requirements
    new_reqs = get_requires(config_settings=requirements.config_settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 303, in __init__
    _Distribution.__init__(self, dist_attrs)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
    self.finalize_options()
  File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 654, in finalize_options
    ep(self)
  File "/usr/lib/python3.12/site-packages/versioningit/hook.py", line 28, in setuptools_finalizer
    raise RuntimeError(
RuntimeError: 
versioningit could not find a version for the project in /home/sagitter/rpmbuild/BUILD/cclib-1.8.1!

You may be installing from a shallow clone, in which case you need to unshallow it first.

Alternatively, you may be installing from a Git archive, which is not supported by default.  Install from a git+https://... URL instead.
```

**Comment by berquist** [comment]
I can reproduce this if I download the source code (last entry) from the release which is missing `.git`.  This may be avoidable with a patch that creates the one-line `cclib/_version.py` which only contains `__version__ = "1.8.1"`.

![Screenshot from 2024-06-20 22-04-12](https://github.com/cclib/cclib/assets/727571/0c36e0d0-a7fc-4ac8-8a4c-efdd8e144a7c)

If you build from the sdist, `cclib-1.8.1.tar.gz`, I don't think versioningit executes, since the autogenerated `cclib/_version.py` is present and the install proceeds, but you may still need to patch the versioningit version.  Installing from the sdist is preferable.

The pin is still worth removing, which is done in #1445.

**Comment by berquist** [comment]
Yes, I see the archive is being downloaded rather than the sdist: https://src.fedoraproject.org/rpms/python-cclib/blob/rawhide/f/python-cclib.spec#_43

A problem with using the sdist is that you would not be able to run the check, since the test data is not a part of the sdist (maybe it should be).

Another possibility, if you don't want to vendor `_version.py`, is to `git clone -b v1.8.1 ...`.  Or, download the sdist and just take `_version.py` from it.

**Comment by sagitter** [comment]
Thank you.

**Comment by berquist** [comment]
This auto closed because the PR was merged, but @sagitter please reopen if you're still having trouble.

I will look to see what other projects using versioningit do, because this means the source code download from GitHub as-is is broken due to the stripped-out `.git`.
