### ISSUE TITLE
versioningit pain

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#1460]
versioningit has been a source of pain since I introduced it (https://github.com/cclib/cclib/pull/1373).

What the package does, as part of https://github.com/cclib/cclib/blob/ee91131e9c278081d1ff88fa763d3c2b5e501da6/pyproject.toml#L68, is to determine the version of the working copy of the source code from the local Git history and make it so `cclib.__version__` works.

This operation does not work as currently implemented in cclib when one has a copy of the source code that is missing a full `.git` directory as discovered in #1444.  `cclib/_version.py` is written when doing a source or wheel build in a Git checkout, but the GitHub "Source code" entries do not have it, and the source/wheel build would also fail when `.git` is missing.

The need to generate this file also created cryptic errors when devs where using an existing venv with an editable install.  In fact, in order to always have the correct version available, one would always have to be reinstalling after every commit.  (Though, the need for the version like this is tiny.)

`nix build` currently produces, once I add `versioningit` and `git`,
```
python3.11-cclib> Sourcing python-remove-tests-dir-hook
python3.11-cclib> Sourcing python-catch-conflicts-hook.sh
python3.11-cclib> Sourcing python-remove-bin-bytecode-hook.sh
python3.11-cclib> Sourcing pypa-build-hook
python3.11-cclib> Using pypaBuildPhase
python3.11-cclib> Sourcing python-runtime-deps-check-hook
python3.11-cclib> Using pythonRuntimeDepsCheckHook
python3.11-cclib> Sourcing pypa-install-hook
python3.11-cclib> Using pypaInstallPhase
python3.11-cclib> Sourcing python-imports-check-hook.sh
python3.11-cclib> Using pythonImportsCheckPhase
python3.11-cclib> Sourcing python-namespaces-hook
python3.11-cclib> Sourcing python-catch-conflicts-hook.sh
python3.11-cclib> Sourcing pytest-check-hook
python3.11-cclib> Using pytestCheckPhase
python3.11-cclib> Running phase: unpackPhase
python3.11-cclib> unpacking source archive /nix/store/y6d5r9yc43yx3crc80crqc9p9bg1g71b-source
python3.11-cclib> source root is source
python3.11-cclib> setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/tools/versioningit_override.py
python3.11-cclib> Running phase: patchPhase
python3.11-cclib> Running phase: updateAutotoolsGnuConfigScriptsPhase
python3.11-cclib> Running phase: configurePhase
python3.11-cclib> no configure script, doing nothing
python3.11-cclib> Running phase: buildPhase
python3.11-cclib> Executing pypaBuildPhase
python3.11-cclib> Creating a wheel...
python3.11-cclib> * Getting build dependencies for wheel...
python3.11-cclib> Traceback (most recent call last):
python3.11-cclib>   File "/nix/store/5ixrvnvwsz2jw28hi9s00kbpprs632dp-python3.11-versioningit-2.3.0/lib/python3.11/site-packages/versioningit/git.py", line 146, in ensure_is_repo
python3.11-cclib>     self.read(
python3.11-cclib>   File "/nix/store/5ixrvnvwsz2jw28hi9s00kbpprs632dp-python3.11-versioningit-2.3.0/lib/python3.11/site-packages/versioningit/git.py", line 178, in read
python3.11-cclib>     return readcmd("git", *args, cwd=str(self.path), **kwargs)
python3.11-cclib>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python3.11-cclib>   File "/nix/store/5ixrvnvwsz2jw28hi9s00kbpprs632dp-python3.11-versioningit-2.3.0/lib/python3.11/site-packages/versioningit/util.py", line 71, in readcmd
python3.11-cclib>     s = runcmd(*args, stdout=subprocess.PIPE, text=True, **kwargs).stdout
python3.11-cclib>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python3.11-cclib>   File "/nix/store/5ixrvnvwsz2jw28hi9s00kbpprs632dp-python3.11-versioningit-2.3.0/lib/python3.11/site-packages/versioningit/util.py", line 66, in runcmd
python3.11-cclib>     return subprocess.run(arglist, **kwargs)
python3.11-cclib>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python3.11-cclib>   File "/nix/store/3v2ch16fkl50i85n05h5ckss8pxx6836-python3-3.11.8/lib/python3.11/subprocess.py", line 571, in run
python3.11-cclib>     raise CalledProcessError(retcode, process.args,
python3.11-cclib> subprocess.CalledProcessError: Command '['git', 'rev-parse', '--is-inside-work-tree']' returned non-zero exit status 128.
python3.11-cclib> During handling of the above exception, another exception occurred:
python3.11-cclib> Traceback (most recent call last):
python3.11-cclib>   File "/nix/store/5ixrvnvwsz2jw28hi9s00kbpprs632dp-python3.11-versioningit-2.3.0/lib/python3.11/site-packages/versioningit/core.py", line 259, in run
python3.11-cclib>     description = self.do_vcs()
python3.11-cclib>                   ^^^^^^^^^^^^^
python3.11-cclib>   File "/nix/store/5ixrvnvwsz2jw28hi9s00kbpprs632dp-python3.11-versioningit-2.3.0/lib/python3.11/site-packages/versioningit/core.py", line 323, in do_vcs
python3.11-cclib>     description = self.vcs(project_dir=self.project_dir)
python3.11-cclib>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python3.11-cclib>   File "/nix/store/5ixrvnvwsz2jw28hi9s00kbpprs632dp-python3.11-versioningit-2.3.0/lib/python3.11/site-packages/versioningit/methods.py", line 162, in __call__
python3.11-cclib>     return self.method(params=self.params, **kwargs)
python3.11-cclib>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python3.11-cclib>   File "/nix/store/5ixrvnvwsz2jw28hi9s00kbpprs632dp-python3.11-versioningit-2.3.0/lib/python3.11/site-packages/versioningit/git.py", line 221, in describe_git
python3.11-cclib>     repo.ensure_is_repo()
python3.11-cclib>   File "/nix/store/5ixrvnvwsz2jw28hi9s00kbpprs632dp-python3.11-versioningit-2.3.0/lib/python3.11/site-packages/versioningit/git.py", line 156, in ensure_is_repo
python3.11-cclib>     raise NotVCSError(f"{self.path} is not in a Git repository")
python3.11-cclib> versioningit.errors.NotVCSError: /build/source is not in a Git repository
python3.11-cclib> During handling of the above exception, another exception occurred:
python3.11-cclib> Traceback (most recent call last):
python3.11-cclib>   File "/nix/store/5ixrvnvwsz2jw28hi9s00kbpprs632dp-python3.11-versioningit-2.3.0/lib/python3.11/site-packages/versioningit/core.py", line 543, in get_version_from_pkg_info
python3.11-cclib>     Path(project_dir, "PKG-INFO").read_text(encoding="utf-8")
python3.11-cclib>   File "/nix/store/3v2ch16fkl50i85n05h5ckss8pxx6836-python3-3.11.8/lib/python3.11/pathlib.py", line 1058, in read_text
python3.11-cclib>     with self.open(mode='r', encoding=encoding, errors=errors) as f:
python3.11-cclib>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python3.11-cclib>   File "/nix/store/3v2ch16fkl50i85n05h5ckss8pxx6836-python3-3.11.8/lib/python3.11/pathlib.py", line 1044, in open
python3.11-cclib>     return io.open(self, mode, buffering, encoding, errors, newline)
python3.11-cclib>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python3.11-cclib> FileNotFoundError: [Errno 2] No such file or directory: '/build/source/PKG-INFO'
python3.11-cclib> During handling of the above exception, another exception occurred:
python3.11-cclib> Traceback (most recent call last):
python3.11-cclib>   File "/nix/store/5ixrvnvwsz2jw28hi9s00kbpprs632dp-python3.11-versioningit-2.3.0/lib/python3.11/site-packages/versioningit/hook.py", line 23, in setuptools_finalizer
python3.11-cclib>     report = vgit.run(write=True, fallback=True)
python3.11-cclib>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python3.11-cclib>   File "/nix/store/5ixrvnvwsz2jw28hi9s00kbpprs632dp-python3.11-versioningit-2.3.0/lib/python3.11/site-packages/versioningit/core.py", line 282, in run
python3.11-cclib>     version=get_version_from_pkg_info(self.project_dir)
python3.11-cclib>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python3.11-cclib>   File "/nix/store/5ixrvnvwsz2jw28hi9s00kbpprs632dp-python3.11-versioningit-2.3.0/lib/python3.11/site-packages/versioningit/core.py", line 546, in get_version_from_pkg_info
python3.11-cclib>     raise NotSdistError(f"{project_dir} does not contain a PKG-INFO file")
python3.11-cclib> versioningit.errors.NotSdistError: /build/source does not contain a PKG-INFO file
python3.11-cclib> During handling of the above exception, another exception occurred:
python3.11-cclib> Traceback (most recent call last):
python3.11-cclib>   File "/nix/store/p6bzclivar1jspgynxs4f05fzd9w5cm6-python3.11-pyproject-hooks-1.0.0/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
python3.11-cclib>     main()
python3.11-cclib>   File "/nix/store/p6bzclivar1jspgynxs4f05fzd9w5cm6-python3.11-pyproject-hooks-1.0.0/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
python3.11-cclib>     json_out['return_val'] = hook(**hook_input['kwargs'])
python3.11-cclib>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python3.11-cclib>   File "/nix/store/p6bzclivar1jspgynxs4f05fzd9w5cm6-python3.11-pyproject-hooks-1.0.0/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
python3.11-cclib>     return hook(config_settings)
python3.11-cclib>            ^^^^^^^^^^^^^^^^^^^^^
python3.11-cclib>   File "/nix/store/bvqadys5w6dallgim0y8y98h05b7kfn7-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
python3.11-cclib>     return self._get_build_requires(config_settings, requirements=['wheel'])
python3.11-cclib>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python3.11-cclib>   File "/nix/store/bvqadys5w6dallgim0y8y98h05b7kfn7-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
python3.11-cclib>     self.run_setup()
python3.11-cclib>   File "/nix/store/bvqadys5w6dallgim0y8y98h05b7kfn7-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
python3.11-cclib>     exec(code, locals())
python3.11-cclib>   File "<string>", line 1, in <module>
python3.11-cclib>   File "/nix/store/bvqadys5w6dallgim0y8y98h05b7kfn7-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
python3.11-cclib>     return distutils.core.setup(**attrs)
python3.11-cclib>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python3.11-cclib>   File "/nix/store/bvqadys5w6dallgim0y8y98h05b7kfn7-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 147, in setup
python3.11-cclib>     _setup_distribution = dist = klass(attrs)
python3.11-cclib>                                  ^^^^^^^^^^^^
python3.11-cclib>   File "/nix/store/bvqadys5w6dallgim0y8y98h05b7kfn7-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/dist.py", line 303, in __init__
python3.11-cclib>     _Distribution.__init__(self, dist_attrs)
python3.11-cclib>   File "/nix/store/bvqadys5w6dallgim0y8y98h05b7kfn7-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
python3.11-cclib>     self.finalize_options()
python3.11-cclib>   File "/nix/store/bvqadys5w6dallgim0y8y98h05b7kfn7-python3.11-setuptools-69.0.3/lib/python3.11/site-packages/setuptools/dist.py", line 654, in finalize_options
python3.11-cclib>     ep(self)
python3.11-cclib>   File "/nix/store/5ixrvnvwsz2jw28hi9s00kbpprs632dp-python3.11-versioningit-2.3.0/lib/python3.11/site-packages/versioningit/hook.py", line 28, in setuptools_finalizer
python3.11-cclib>     raise RuntimeError(
python3.11-cclib> RuntimeError:
python3.11-cclib> versioningit could not find a version for the project in /build/source!
python3.11-cclib> You may be installing from a shallow clone, in which case you need to unshallow it first.
python3.11-cclib> Alternatively, you may be installing from a Git archive, which is not supported by default.  Install from a git+https://... URL instead.
python3.11-cclib> ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
error: builder for '/nix/store/v6ki7w67jrhkl9ljn8w1v48054k142jk-python3.11-cclib-1.8.1.drv' failed with exit code 1;
       last 10 log lines:
       > RuntimeError:
       > versioningit could not find a version for the project in /build/source!
       >
       > You may be installing from a shallow clone, in which case you need to unshallow it first.
       >
       > Alternatively, you may be installing from a Git archive, which is not supported by default.  Install from a git+https://... URL instead.
       >
       >
       >
       > ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
       For full logs, run 'nix log /nix/store/v6ki7w67jrhkl9ljn8w1v48054k142jk-python3.11-cclib-1.8.1.drv'.
```
`/nix/store/y6d5r9yc43yx3crc80crqc9p9bg1g71b-source` is the same idea as the GitHub source download: it's the working copy with `.git` removed.

The goal is to either switch to another package that avoids this problem altogether, or come up with a workaround.

**Comment by berquist** [comment]
In order for push workflows in forks to work, the latest tag needs to be present in the fork.  People shouldn't need more commits aside from the latest default branch commit in order to run their own CI.
