### ISSUE TITLE
Molpro: crash reading Avogadro-generated output

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#239]
I wanted to calculate the energy of a molecule, but have no idea how to hand-write a Molpro input, so I used the Avogadro input generator for RHF/STO-3G. This is the `ccget` output:

```
Attempting to read molpro.out
Traceback (most recent call last):
  File "/usr/bin/ccget", line 180, in <module>
    ccget()
  File "/usr/bin/ccget", line 153, in ccget
    data = ccread(filename, **kwargs)
  File "/usr/lib/python3.5/site-packages/cclib/parser/ccio.py", line 107, in ccread
    return log.parse()
  File "/usr/lib/python3.5/site-packages/cclib/parser/logfileparser.py", line 309, in parse
    self.extract(inputfile, line)
  File "/usr/lib/python3.5/site-packages/cclib/parser/molproparser.py", line 198, in extract
    funcatom = int(line_nuc)
ValueError: invalid literal for int() with base 10: ''
```
[CHONHSH_HF_STO-3G.out](https://github.com/cclib/cclib/files/116444/CHONHSH_HF_STO-3G.txt)

I found https://github.com/cclib/cclib/issues/40, but Molpro only generated a single file.

**Comment by langner** [comment]
Fixed.
