### ISSUE TITLE
DALTON: error with reading atoms?

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#285]
This input:

```
INTGRL
---
---
Atomtypes=2 Angstrom Charge=2 Nosymmetry Integrals=1.00D-15
Charge=3.0 Atoms=1 Blocks=2 0 1
Li  0.0000  0.0000  0.0000
    1    1
0.636289700 1.0
Charge=1.0 Atoms=1 Blocks=1 1
H   0.0000  0.0000  1.5949
    1    1
3.42525091 1.0

**DALTON INPUT
.RUN ALL
**WAVE FUNCTIONS
.HF
*SCF IN
.THRESH
1.0D-07
.MAX DIIS ITERATIONS
200
.NOQCSCF
*DFT INPUT
.ULTRAF
*ORBITAL INPUT
.PUNCHOUTPUTORBITALS
**INTEGRAL
.KINENE
.1ELPOT
.DIPLEN
.DIPVEL
.ANGMOM
.SPIN-ORBIT
.ELGDIA
.FC
.SD
.PROPRI
**RESPONSE
.TDA
*LINEAR
.THCLR
1.0D-6
.DIPLEN
.DIPMAG
.DIPVEL
.FERMI
.SPIN-D
.SPIN-O
.PROPRT
X1SPNORB
.PROPRT
Y1SPNORB
.PROPRT
Z1SPNORB
.PRINT
2000
**END OF DALTON INPUT
```

leads to this error:

```
Attempting to read dalton_response_tda_singlet.out
Traceback (most recent call last):
  File "/usr/bin/ccget", line 180, in <module>
    ccget()
  File "/usr/bin/ccget", line 153, in ccget
    data = ccread(filename, **kwargs)
  File "/usr/lib/python3.5/site-packages/cclib/parser/ccio.py", line 107, in ccread
    return log.parse()
  File "/usr/lib/python3.5/site-packages/cclib/parser/logfileparser.py", line 309, in parse
    self.extract(inputfile, line)
  File "/usr/lib/python3.5/site-packages/cclib/parser/daltonparser.py", line 232, in extract
    iatoms = cols.index('atoms')
ValueError: 'atoms' is not in list
```

My hypothesis is that it has something to do with the mixed coordinate/basis (`INTGRL`) input.

**Comment by langner** [comment]
I guess you mean the output Dalton creates from this input? Can you upload it and add it as a regression when the fix is in?

**Comment by berquist** [comment]
Yes, of course; I'll try and get to it over the weekend.

**Comment by berquist** [comment]
Minimal input to reproduce:

```
INTGRL
---
---
Atomtypes=2 Angstrom Charge=2 Nosymmetry Integrals=1.00D-15
Charge=3.0 Atoms=1 Blocks=2 0 1
Li  0.0000  0.0000  0.0000
    1    1
0.636289700 1.0
Charge=1.0 Atoms=1 Blocks=1 1
H   0.0000  0.0000  1.5949
    1    1
3.42525091 1.0

**DALTON INPUT
.RUN ALL
**WAVE FUNCTIONS
.HF
**END OF DALTON INPUT
```

**Comment by berquist** [comment]
Fix is https://github.com/cclib/cclib/pull/287, regressions are https://github.com/cclib/cclib-data/pull/38.

**Comment by langner** [comment]
Fixed.
