### ISSUE TITLE
Typo in MOPAC parser

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#346]
Trying to read a frequency output made with

```
PM7 CHARGE=+1 SINGLET PRECISE LARGE AUX ALLVEC PRTXYZ FORCE
```

```
[eric@copper]$ ccget --list 9S3_uuu_Cs_cation_freq_PM7.out
Attempting to read 9S3_uuu_Cs_cation_freq_PM7.out
Traceback (most recent call last):
  File "/usr/bin/ccget", line 193, in <module>
    ccget()
  File "/usr/bin/ccget", line 156, in ccget
    data = ccread(filename, **kwargs)
  File "/usr/lib/python3.6/site-packages/cclib/io/ccio.py", line 121, in ccread
    return log.parse()
  File "/usr/lib/python3.6/site-packages/cclib/parser/logfileparser.py", line 308, in parse
    self.extract(inputfile, line)
  File "/usr/lib/python3.6/site-packages/cclib/parser/mopacparser.py", line 194, in extract
    sym = line.split[2]
TypeError: 'builtin_function_or_method' object is not subscriptable
```

**Comment by langner** [comment]
Can you add the output file to here or to regrsesions?
