### ISSUE TITLE
Multifile crash

### ISSUE THREAD

**Issue by InvalidPointer** [cclib/cclib#350]
Tried to test multifile mode and encountered such error:

`Traceback (most recent call last):
  File "src/scripts/ccget", line 193, in <module>
    ccget()
  File "src/scripts/ccget", line 156, in ccget
    data = ccread(filename, **kwargs)
  File "/Users/invalidpointer/anaconda/envs/cclib-test/lib/python3.5/site-packages/cclib/io/ccio.py", line 112, in ccread
    log = ccopen(source, *args, **kargs)
  File "/Users/invalidpointer/anaconda/envs/cclib-test/lib/python3.5/site-packages/cclib/io/ccio.py", line 190, in ccopen
    inputfile.seek(0, 0)
AttributeError: 'FileInput' object has no attribute 'seek'`

I think it happens because in case of multiple files "openlogfile" function returns FileInput object which doesn't have "seek" method.

**Comment by ATenderholt** [comment]
Can you provide a few more details? Which files did you try opening this way and what was the exact command? Which version are you using (e.g. 1.5, commit b0e2bf9, etc)?

**Comment by InvalidPointer** [comment]
Yes, of course. The exact command was:
`python src/scripts/ccget --multi natom data/Molpro/basicMolpro2012/h2o_mp2.out data/Molpro/basicMolpro2012/h2o_mp3.out`
I was using version b0e2bf927d2fb13ae380cbbd7c512381191a1016.
