### ISSUE TITLE
Exception while parsing files in multi mode

### ISSUE THREAD

**Issue by InvalidPointer** [cclib/cclib#356]
Modified test to  check parse result and get exception. On latest commit (112be5e).
Commandline: `python ./test_io.py`
```
ERROR: test_list_of_filenames (testccio.ccopenTest)
Can we ccopen a list of filenames (https://github.com/cclib/cclib/issues/350)?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "io/testccio.py", line 75, in test_list_of_filenames
    self.assertIsNotNone(self.ccopen(filepaths).parse())
  File "/Users/invalidpointer/anaconda/envs/cclib-test/lib/python3.5/site-packages/cclib/parser/logfileparser.py", line 336, in parse
    data = self.datatype(attributes=self.__dict__)
  File "/Users/invalidpointer/anaconda/envs/cclib-test/lib/python3.5/site-packages/cclib/parser/data.py", line 312, in __init__
    super(ccData_optdone_bool, self).__init__(*args, **kwargs)
  File "/Users/invalidpointer/anaconda/envs/cclib-test/lib/python3.5/site-packages/cclib/parser/data.py", line 180, in __init__
    self.setattributes(attributes)
  File "/Users/invalidpointer/anaconda/envs/cclib-test/lib/python3.5/site-packages/cclib/parser/data.py", line 315, in setattributes
    invalid = super(ccData_optdone_bool, self).setattributes(*args, **kwargs)
  File "/Users/invalidpointer/anaconda/envs/cclib-test/lib/python3.5/site-packages/cclib/parser/data.py", line 252, in setattributes
    self.arrayify()
  File "/Users/invalidpointer/anaconda/envs/cclib-test/lib/python3.5/site-packages/cclib/parser/data.py", line 208, in arrayify
    setattr(self, k, numpy.array(getattr(self, k), precision))
ValueError: setting an array element with a sequence.
```

**Comment by langner** [comment]
Which version of Python was this with? I can't reproduce.

**Comment by InvalidPointer** [comment]
I was using `Python 3.5.3`
Test was modified such way: `self.assertIsNotNone(self.ccopen(filepaths).parse())`
