### ISSUE TITLE
Error importing cclib in python2.7.10

### ISSUE THREAD

**Issue by gaursagar** [cclib/cclib#375]
Hi, I encountered an `ImportError` while trying to import cclib using `python 2.7.10` (this version ships with OSX by default). Simplest solution to avoid this is an upgrade to `python 2.7.13+`.

cclib documentation however states that python 2.7 is still tested. I believe making this clear in the [requirements](https://cclib.github.io/tutorial.html#requirements) page, would help new users.

Error Obtained:

```python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.`
>>> import cclib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/cclib/__init__.py", line 28, in <module>
    from . import parser
  File "/usr/local/lib/python2.7/site-packages/cclib/parser/__init__.py", line 17, in <module>
    from .adfparser import ADF
  File "/usr/local/lib/python2.7/site-packages/cclib/parser/adfparser.py", line 15, in <module>
    import numpy
  File "/usr/local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python2.7/site-packages/numpy/core/__init__.py", line 72, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/__init__.py", line 12, in <module>
    from . import decorators as dec
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/decorators.py", line 20, in <module>
    from .utils import SkipTest, assert_warns
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 15, in <module>
    from tempfile import mkdtemp, mkstemp
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
```

**Comment by langner** [comment]
Please see http://stackoverflow.com/questions/34386527/symbol-not-found-pycodecinfo-getincrementaldecoder

Apparently it's a caching problem specific to OSX. Have you tried logging out and back in?

**Comment by gaursagar** [comment]
> Have you tried logging out and back in?

I hadn't, but the import seems to be working fine after  restarting the machine. 

If there is no need to make any changes to documentation, this issue can be closed.
