### ISSUE TITLE
Molden writer tests not passing

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#404]
I am getting failures in the new Molden tests when doing `python testall.py` with Open Babel installed via `pip` in my virtualenv.

```
======================================================================
ERROR: test_atoms_section_size (testmoldenwriter.MOLDENTest)                
Check if size of Atoms section is equal to expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "io/testmoldenwriter.py", line 43, in test_atoms_section_size
    writer = cclib.io.moldenwriter.MOLDEN(data)
  File "/media/Backup/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/cclib/io/filewriter.py", line 54, in __init__
    self.obmol, self.pbmol = self._make_openbabel_from_ccdata()
  File "/media/Backup/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/cclib/io/filewriter.py", line 73, in _make_openbabel_from_ccdata
    mult=self.ccdata.mult)
  File "/media/Backup/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/cclib/bridge/cclib2openbabel.py", line 45, in makeopenbabel
    obmol.SetTotalCharge(charge)
TypeError: in method 'OBMol_SetTotalCharge', argument 2 of type 'int'

======================================================================
ERROR: test_gto_section_size (testmoldenwriter.MOLDENTest)
Check if size of GTO section is equal to expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "io/testmoldenwriter.py", line 52, in test_gto_section_size
    writer = cclib.io.moldenwriter.MOLDEN(data)
  File "/media/Backup/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/cclib/io/filewriter.py", line 54, in __init__
    self.obmol, self.pbmol = self._make_openbabel_from_ccdata()
  File "/media/Backup/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/cclib/io/filewriter.py", line 73, in _make_openbabel_from_ccdata
    mult=self.ccdata.mult)
  File "/media/Backup/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/cclib/bridge/cclib2openbabel.py", line 45, in makeopenbabel
    obmol.SetTotalCharge(charge)
TypeError: in method 'OBMol_SetTotalCharge', argument 2 of type 'int'

======================================================================
ERROR: test_missing_attribute_error (testmoldenwriter.MOLDENTest)
Check if MissingAttributeError is raised as expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "io/testmoldenwriter.py", line 36, in test_missing_attribute_error
    cclib.io.moldenwriter.MOLDEN(data)
  File "/media/Backup/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/cclib/io/filewriter.py", line 54, in __init__
    self.obmol, self.pbmol = self._make_openbabel_from_ccdata()
  File "/media/Backup/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/cclib/io/filewriter.py", line 70, in _make_openbabel_from_ccdata
    obmol = makeopenbabel(self.ccdata.atomcoords,
AttributeError: 'ccData_optdone_bool' object has no attribute 'atomcoords'

======================================================================
ERROR: test_mo_section_size (testmoldenwriter.MOLDENTest)
Check if size of MO section is equal to expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "io/testmoldenwriter.py", line 68, in test_mo_section_size
    writer = cclib.io.moldenwriter.MOLDEN(data)
  File "/media/Backup/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/cclib/io/filewriter.py", line 54, in __init__
    self.obmol, self.pbmol = self._make_openbabel_from_ccdata()
  File "/media/Backup/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/cclib/io/filewriter.py", line 73, in _make_openbabel_from_ccdata
    mult=self.ccdata.mult)
  File "/media/Backup/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/cclib/bridge/cclib2openbabel.py", line 45, in makeopenbabel
    obmol.SetTotalCharge(charge)
TypeError: in method 'OBMol_SetTotalCharge', argument 2 of type 'int'

======================================================================
ERROR: test_molden_cclib_diff (testmoldenwriter.MOLDENTest)
Check if file written by cclib matched file written by Molden.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "io/testmoldenwriter.py", line 101, in test_molden_cclib_diff
    cclib_out = cclib.io.moldenwriter.MOLDEN(data).generate_repr()
  File "/media/Backup/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/cclib/io/filewriter.py", line 54, in __init__
    self.obmol, self.pbmol = self._make_openbabel_from_ccdata()
  File "/media/Backup/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/cclib/io/filewriter.py", line 73, in _make_openbabel_from_ccdata
    mult=self.ccdata.mult)
  File "/media/Backup/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/cclib/bridge/cclib2openbabel.py", line 45, in makeopenbabel
    obmol.SetTotalCharge(charge)
TypeError: in method 'OBMol_SetTotalCharge', argument 2 of type 'int'

----------------------------------------------------------------------
```

**Comment by gaursagar** [comment]
Thanks for pointing out. Issue was `obmol.SetTotalCharge` in `cclib2molden.py` accepts integer value, and was failing for a `float` being passed. This issue wasn't caught before because none of the files in tests had a charge.

The other change in `filewriter` is to ensure that `makeopenbabel` does not break when unittests to check `MissingAttributeErrors` are run.
