### ISSUE TITLE
Travis not catching errors during tests

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#444]
In https://travis-ci.org/cclib/cclib/jobs/287875374 for https://github.com/cclib/cclib/pull/442, there are a few clear failures that Travis isn't catching; it says the PR passed. Something must be wrong with the shell script or our testing environment.

```
======================================================================
ERROR: test_list_of_filenames (testccio.ccopenTest)
Can we ccopen a list of filenames (https://github.com/cclib/cclib/issues/350)?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "io/testccio.py", line 81, in test_list_of_filenames
    self.assertIsNotNone(self.ccopen(filepaths).parse())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/cclib/parser/logfileparser.py", line 311, in parse
    self.extract(inputfile, line)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/cclib/parser/molproparser.py", line 890, in extract
    while lines_read < self.natom:
AttributeError: 'Molpro' object has no attribute 'natom'

======================================================================
ERROR: test_multi_url_io (testccio.ccopenTest)
Does the function works with multiple URLs such good as with multiple filenames?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "io/testccio.py", line 103, in test_multi_url_io
    self.ccopen([os.path.join(fpath, fname) for fname in filenames], quiet=True)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/cclib/io/ccio.py", line 213, in ccopen
    inputfile = logfileparser.openlogfile(source)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/cclib/parser/logfileparser.py", line 173, in openlogfile
    fileobject = fileinput.input(filename, openhook=fileinput.hook_compressed)
  File "/opt/python/3.6.3/lib/python3.6/fileinput.py", line 93, in input
    raise RuntimeError("input() already active")
RuntimeError: input() already active
```

and then another failure during the visual tests due to `self.natom` in the Molpro parser.

Permanent copy of the log: [log.txt](https://github.com/cclib/cclib/files/1384971/log.txt)

**Comment by langner** [comment]
Maybe #445 will help?

**Comment by langner** [comment]
By the look of #442, #445 seems to have helped.

**Comment by berquist** [comment]
Yes, though I just realized that `set -e` would have solved this as well.
