### ISSUE TITLE
Parsing error with some double precision floats in Gaussian

### ISSUE THREAD

**Issue by jaimergp** [cclib/cclib#460]
Apparently, Gaussian sometimes outputs double precision floats without the exponent part, which results in a parsing error in `Logfile.float`. I don't know if it's a Gaussian bug, but this weird behaviour happens from time to time. Is that standard Fortran behaviour? Should the exponent be assumed to be `+-01`?

I cannot provide a full example right now, but here is an excerpt from the offending file:

Gaussian version & input headers
```
 ******************************************
 Gaussian 09:  AS64L-G09RevD.01 24-Apr-2013
                27-Sep-2017 
 ******************************************
 %nprocshared=8
 Will use up to    8 processors via shared memory.
 %mem=32GB
 ----------------------------------------------------------------------
 #p opt=(calcfc,modredundant,ts,noeigentest) freq=noraman SCRF=(SMD,SOL
 VENT=generic,read) GEN 5D pseudo=read scfcyc=60 scf=xqc B3LYP Empirica
 lDispersion=GD3
 ----------------------------------------------------------------------
 1/5=1,10=4,11=1,14=-1,18=120,26=3,38=1,40=2/1,3;
 2/9=110,12=2,17=6,18=5,40=1/2;
 3/5=7,8=1,11=2,16=1,17=8,25=1,30=1,70=32203,71=2,72=-2,74=-5,124=31,140=1/1,2,3;
 4//1;
 5/5=2,7=60,8=3,13=1,38=5/2,8;
 8/6=4,10=90,11=11/1;
 11/6=1,8=1,9=11,15=111,16=1/1,2,10;
 10/6=1,13=1/2;
 6/7=2,8=2,9=2,10=2,28=1/1;
 7/10=1,18=20,25=1/1,2,3,16;
 1/5=1,10=4,11=1,14=-1,18=20,26=3/3(2);
 2/9=110/2;
 99//99;
 2/9=110/2;
 3/5=7,6=1,8=1,11=2,16=1,17=8,25=1,30=1,70=32205,71=1,72=-2,74=-5,82=7,124=31/1,2,3;
 4/5=5,16=3,69=1/1;
 5/5=2,7=60,8=3,13=1,38=5/2,8;
 7//1,2,3,16;
 1/5=1,11=1,14=-1,18=20,26=3/3(-5);
 2/9=110/2;
 6/7=2,8=2,9=2,10=2,19=2,28=1/1;
 99/9=1/99;
```

Offending line and its context:

```
 E= -2574.14648111538     Delta-E=       -0.000000000067 Rises=F Damp=F
 DIIS: error= 7.03D-08 at cycle  17 NSaved=  17.
 NSaved=17 IEnMin=17 EnMin= -2574.14648111538     IErMin=17 ErrMin= 7.03D-08
 ErrMax= 7.03D-08  0.00D+00 EMaxC= 1.00D-01 BMatC= 9.00D-12 BMatP= 2.59D-11
 IDIUse=1 WtCom= 1.00D+00 WtEn= 0.00D+00
 Coeff-Com: -0.200D-05 0.444D-04 0.451D-04-0.845D-04-0.170D-03-0.399D-03
 Coeff-Com: -0.234D-02-0.261D-02 0.324D-02 0.877D-02 0.834D-02-0.107D-01
 Coeff-Com: -0.465D-01-0.578D-01 0.474D-01 0.445D+00 0.608D+00
 Coeff:     -0.200D-05 0.444D-04 0.451D-04-0.845D-04-0.170D-03-0.399D-03
 Coeff:     -0.234D-02-0.261D-02 0.324D-02 0.877D-02 0.834D-02-0.107D-01
 Coeff:     -0.465D-01-0.578D-01 0.474D-01 0.445D+00 0.608D+00
 Gap=     0.069 Goal=   None    Shift=    0.000
 RMSDP=8.56D- E= -2574.14922100993     Delta-E=       -0.000000136863 Rises=F Damp=F
 DIIS: error= 6.27D-06 at cycle   9 NSaved=   9.
 NSaved= 9 IEnMin= 9 EnMin= -2574.14922100993     IErMin= 9 ErrMin= 6.27D-06
 ErrMax= 6.27D-06  0.00D+00 EMaxC= 1.00D-01 BMatC= 2.70D-08 BMatP= 9.09D-08
 IDIUse=1 WtCom= 1.00D+00 WtEn= 0.00D+00
 Coeff-Com: -0.159D-03 0.488D-02-0.405D-02-0.185D-01-0.609D-01-0.134D+00
 Coeff-Com: -0.930D-01 0.399D+00 0.907D+00
 Coeff:     -0.159D-03 0.488D-02-0.405D-02-0.185D-01-0.609D-01-0.134D+00
 Coeff:     -0.930D-01 0.399D+00 0.907D+00
 Gap=     0.065 Goal=   None    Shift=    0.000
 RMSDP=5.26D-07 MaxDP=1.64D-04 DE=-1.37D-07 OVMax= 2.38D-04
```

Notice the middle `RMSDP` line. 

The traceback:

```
$> ccget --list buggyfile.log
Attempting to read buggyfile.log
Traceback (most recent call last):
  File "/home/jrodriguez/.local/anaconda/envs/supporting-dev/bin/ccget", line 209, in <module>
    ccget()
  File "/home/jrodriguez/.local/anaconda/envs/supporting-dev/bin/ccget", line 165, in ccget
    data = ccread(filename, **kwargs)
  File "/home/jrodriguez/.local/anaconda/envs/supporting-dev/lib/python3.6/site-packages/cclib/io/ccio.py", line 158, in ccread
    return log.parse()
  File "/home/jrodriguez/.local/anaconda/envs/supporting-dev/lib/python3.6/site-packages/cclib/parser/logfileparser.py", line 311, in parse
    self.extract(inputfile, line)
  File "/home/jrodriguez/.local/anaconda/envs/supporting-dev/lib/python3.6/site-packages/cclib/parser/gaussianparser.py", line 669, in extract
    newlist = [self.float(x.split('=')[1]) for x in parts[0:2]]
  File "/home/jrodriguez/.local/anaconda/envs/supporting-dev/lib/python3.6/site-packages/cclib/parser/gaussianparser.py", line 669, in <listcomp>
    newlist = [self.float(x.split('=')[1]) for x in parts[0:2]]
  File "/home/jrodriguez/.local/anaconda/envs/supporting-dev/lib/python3.6/site-packages/cclib/parser/logfileparser.py", line 403, in float
    return float(number.replace("D", "E"))
ValueError: could not convert string to float: '9.34E-'
```
How should this be addressed? At the `Gaussian` parser level or at `Logfile.float` level?

-- edit --
In the same file, other `RMSDP` lines do not provide any value:

```
 Cycle  19  Pass 1  IDiag  1:
 RMSU=  9.66D-10    CP:  1.00D+00  1.10D+00  7.03D-01  4.25D-01  3.44D-01
                    CP:  1.49D+00  2.35D+00  2.34D+00  1.73D+00  1.66D+00
                    CP:  2.05D+00  2.00D+00  2.29D+00  2.31D+00  2.29D+00
                    CP:  2.16D+00  1.82D+00  1.07D+00
 E= -2574.14949279470     Delta-E=       -0.000000000095 Rises=F Damp=F
 DIIS: error= 1.23D-08 at cycle  19 NSaved=  19.
 NSaved=19 IEnMin=16 EnMin= -2574.14949279474     IErMin=19 ErrMin= 1.23D-08
 ErrMax= 1.23D-08  0.00D+00 EMaxC= 1.00D-01 BMatC= 1.89D-13 BMatP= 5.27D-13
 IDIUse=1 WtCom= 1.00D+00 WtEn= 0.00D+00
 Coeff-Com:  0.157D-05-0.361D-04 0.220D-03 0.379D-04 0.257D-03 0.740D-03
 Coeff-Com:  0.123D-02-0.256D-02-0.401D-02-0.197D-02 0.991D-02 0.233D-01
 Coeff-Com:  0.193D-01-0.467D-01-0.124D+00-0.125D+00 0.115D+00 0.458D+00
 Coeff-Com:  0.676D+00
 Coeff:      0.157D-05-0.361D-04 0.220D-03 0.379D-04 0.257D-03 0.740D-03
 Coeff:      0.123D-02-0.256D-02-0.401D-02-0.197D-02 0.991D-02 0.233D-01
 Coeff:      0.193D-01-0.467D-01-0.124D+00-0.125D+00 0.115D+00 0.458D+00
 Coeff:      0.676D+00
 Gap=     0.065 Goal=   None    Shift=    0.000
 RMSDP= E= -2574.14931865182     Delta-E=       -0.000000019540 Rises=F Damp=F
 DIIS: error= 1.01D-06 at cycle  11 NSaved=  11.
 NSaved=11 IEnMin=11 EnMin= -2574.14931865182     IErMin=11 ErrMin= 1.01D-06
 ErrMax= 1.01D-06  0.00D+00 EMaxC= 1.00D-01 BMatC= 1.57D-09 BMatP= 8.53D-09
 IDIUse=1 WtCom= 1.00D+00 WtEn= 0.00D+00
 Coeff-Com: -0.904D-04 0.135D-02-0.625D-03-0.524D-03-0.179D-02-0.235D-01
 Coeff-Com: -0.533D-01-0.176D-01 0.122D+00 0.328D+00 0.646D+00
 Coeff:     -0.904D-04 0.135D-02-0.625D-03-0.524D-03-0.179D-02-0.235D-01
 Coeff:     -0.533D-01-0.176D-01 0.122D+00 0.328D+00 0.646D+00
 Gap=     0.065 Goal=   None    Shift=    0.000
 RMSDP=1.17D-07 MaxDP=3.66D-05 DE=-1.95D-08 OVMax= 6.45D-05
```

**Comment by berquist** [comment]
These are probably Gaussian bugs of some kind. I don't know enough Fortran to say how this is possible.

For us, this sort of thing is handled at the parser level. Since we have no way of calculating or predicting what the value should be (it's $\left \| \mathbf{P}^{(n)} - \mathbf{P}^{(n-1)} \right \|_{2}$), it will need to be set to `numpy.nan`.

**Comment by langner** [comment]
I agree with Eric, we will not compensate for Gaussian bugs. But, if you can provide us with an example output file, we can catch the error and replace the value with a `nan` so at least the parser doesn't fail.

**Comment by jaimergp** [comment]
Here's the file: [cclib-issue-460.log](https://github.com/cclib/cclib/files/1748641/cclib-issue-460.log)

Thanks!

**Comment by berquist** [comment]
The output in this file is pretty messed up. These are all the unique types of lines I could find with `grep 'RMSDP'`:

```
 RMSDP=3.79D-04 MaxDP=4.02D-02              OVMax= 4.31D-02
 RMSDP=1.43D-06 MaxDP=5.44D-04 DE=-6.21D-07 OVMax= 5.76D-04
 RMSDP=2.06D-05 MaxDP=3.84D-03 DE= 4.82D-04 O E= -2574.14897924075     Delta-E=        0.000439804468 Rises=F Damp=F
 RMSDP=8.64D-09 MaxDP=2.65D-06 DE=-1.67D-10 OVMax= 3. E= -2574.14837678675     Delta-E=       -0.000000179038 Rises=F Damp=F
 RMSDP= E= -2574.14931865182     Delta-E=       -0.000000019540 Rises=F Damp=F
 RMSDP=9.34D- E= -2574.14837612206     Delta-E=       -0.000000620705 Rises=F Damp=F
 RMSDP=7.18D-05 Max E= -2574.14797761904     Delta-E=       -0.000000000397 Rises=F Damp=F
 RMSDP=1.85D-06 MaxD E= -2574.14770506975     Delta-E=       -0.042173156160 Rises=F Damp=F
 RMSDP=1.69D-06 MaxDP= E= -2574.14801776548     Delta-E=        0.000023521317 Rises=F Damp=F
 RMSDP=3.80D-08 MaxDP=1 E= -2574.14856570920     Delta-E=       -0.000002960194 Rises=F Damp=F
 RMSDP=4.47D-09 MaxDP=1.40 E= -2574.14915435699     Delta-E=       -0.000255709558 Rises=F Damp=F
 RMSDP=5.54D-08 MaxDP=1.55D-05 DE=-2.55D-0 E= -2574.14854319757     Delta-E=       -0.000929740010 Rises=F Damp=F
 RMSDP=7.20D-09 MaxDP=1.75D-06 DE=- (Enter /QFsoft/applic/GAUSSIAN/g09d.01_pgi11.9-ISTANBUL/g09/l703.exe)
 RMSDP=5.24D-09 MaxDP=1.47D-06 DE=-1.82D-11 OVMax= 2.15 (Enter /QFsoft/applic/GAUSSIAN/g09d.01_pgi11.9-ISTANBUL/g09/l703.exe)
 RMSDP=1.71D-04 MaxDP=1.54D-02    Iteration    2 A^-1*A deviation from unit magnitude is 1.11D-15 for    266.
```

**Comment by berquist** [comment]
* This will trap the numbers in scientific notation: `(-?\d\.\d{2}D[+-]\d{2})`
* This will trap the normal floats: `(-?\d+\.\d{10,})`

**Comment by berquist** [comment]
I've fixed the parsing so that we only take properly-formed values. However, "we will not compensate for Gaussian bugs" is an understatement...it looks like the printing is already messed up by `SCF Done` number 13, so I wouldn't trust anything from this file.

**Comment by langner** [comment]
Thanks!

**Comment by jaimergp** [comment]
Thanks!
