### ISSUE TITLE
Parsing issue in GAMESS-2010 

### ISSUE THREAD

**Issue by gaursagar** [cclib/cclib#483]
Hi,
One of my logfiles was failing to parse today. I am using GAMESS-2010. This is very much an exception, because I have thousands of other similar calculations that parse totally fine.

```python
Traceback (most recent call last):
  File "/usr/local/bin/ccget", line 209, in <module>
    ccget()
  File "/usr/local/bin/ccget", line 165, in ccget
    data = ccread(filename, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cclib/io/ccio.py", line 156, in ccread
    return log.parse()
  File "/usr/local/lib/python3.5/dist-packages/cclib/parser/logfileparser.py", line 311, in parse
    self.extract(inputfile, line)
  File "/usr/local/lib/python3.5/dist-packages/cclib/parser/gamessparser.py", line 982, in extract
    self.nmo = self.nbasis
AttributeError: 'GAMESS' object has no attribute 'nbasis'
```
I am aware cclib doesn't _support_ the 2010 version. Nevertheless I am filing an issue for the sake of record.
(At the moment I cannot check whether this happens in newer versions too)

Log File : [gamess2010_nbasis_error.txt](https://github.com/cclib/cclib/files/1838488/gamess2010_nbasis_error.txt)

Consider closing this issue for now :)

**Comment by berquist** [comment]
The problem is that all the necessary information isn't actually there. I see most of the file as a massive binary blob. If you run `tr -cd '\11\12\15\40-\176' < 483.out > 483_stripped.out` (see [here](https://alvinalexander.com/blog/post/linux-unix/how-remove-non-printable-ascii-characters-file-unix)) to remove it, you can see that the header is missing.
```
 INPUT CARD> H   1.0         -0.81100       -1.55000       -3.30700                         
 INPUT CARD> H   1.0          2.46100       -3.30800       -3.29900                         
 INPUT CARD> H   1.0          0.72300       -3.50800       -3.30100                         
 INPUT CARD> H   1.0          1.22000        2.14100       -3.30400                         
 INPUT CARD>$END                                                                            
           3000000000  WORDS OF MEMORY UNAVAILABLE
 EXECUTION OF GAMESS TERMINATED -ABNORMALLY- AT Tue Mar 20 15:13:50 2018
 CPU     0: STEP CPU TIME=     0.00 TOTAL CPU TIME=        0.0 (    0.0 MIN)
 TOTAL WALL CLOCK TIME=        0.0 SECONDS, CPU UTILIZATION IS   0.00%
 ddikick.x: application process 0 quit unexpectedly.
 ddikick.x: Sending kill signal to DDI processes.
 ddikick.x: Execution terminated due to error(s).
----- accounting info -----
Tue Mar 20 15:13:52 IST 2018
Files used on the master node node16.local were:
-rw-r--r-- 1 sagar deva 2057 Mar 20 15:13 /scratch/sagar/G1110_C111.F05
0.115u 0.076s 0:02.69 6.6%	0+0k 0+0io 10pf+0w
   9  8  0     -916.1202195459    -0.0000074435   0.002485794   0.000121046
  10  9  0     -916.1202216802    -0.0000021343   0.001927956   0.000023980
  11 10  0     -916.1202219189    -0.0000002387   0.000793484   0.000028720
  12 11  0     -916.1202219612    -0.0000000423   0.000311449   0.000009431
  13 12  0     -916.1202219702    -0.0000000091   0.000109965   0.000002390
  14 13  0     -916.1202219712    -0.0000000010   0.000035349   0.000001673
  15 14  0     -916.1202219715    -0.0000000002   0.000031430   0.000000421
  16 15  0     -916.1202219715     0.0000000000   0.000014445   0.000000149
  17 16  0     -916.1202219715     0.0000000000   0.000004984   0.000000072
  18 17  0     -916.1202219715     0.0000000000   0.000003807   0.000000037
  19 18  0     -916.1202219715     0.0000000000   0.000000000   0.000000010

          -----------------
          DENSITY CONVERGED
          -----------------
```

Can you view this properly in a terminal? In less and emacs the binary section is just a bunch of `^@`. Do you have another similar file that parses properly? I don't think this is a bug but there may be an encoding issue.

**Comment by gaursagar** [comment]
@berquist Thanks!.
I couldn't find any other file with such encoding issues. This seems to be a one off weird glitch in the HPC, or some of my scripts.

I'll let you know if something like this happens again.
