### ISSUE TITLE
ccget no longer works

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#497]
Both my virtualenv and system install (from latest git) are broken:
```
[eric@copper]$ ccget --help
Traceback (most recent call last):
  File "/usr/bin/ccget", line 11, in <module>
    load_entry_point('cclib==1.5.3', 'console_scripts', 'ccget')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'scripts.ccget'
```

**Comment by berquist** [comment]
The problem is in commit 4b27568.

**Comment by berquist** [comment]
Ah, the reason this fails for me and testing on my machine no longer works is because it conflicts with a folder on my `PYTHONPATH` called `scripts`.

While this is a problem with _my_ setup, I think we should convert the current folder structure:
```
.
├── data
├── old
├── src
│   ├── cclib
│   │   ├── bridge
│   │   ├── io
│   │   ├── method
│   │   ├── parser
│   │   └── progress
│   ├── cclib.egg-info
│   └── scripts
├── test
│   ├── bridge
│   ├── data
│   ├── io
│   │   └── data
│   ├── method
│   └── parser
└── travis
```
into a more traditional Python package:
```
.
├── data
├── old
├── cclib
│   ├── bridge
│   ├── io
│   ├── method
│   ├── parser
│   ├── progress
│   └── scripts
├── cclib.egg-info
├── test
│   ├── bridge
│   ├── data
│   ├── io
│   │   └── data
│   ├── method
│   └── parser
└── travis
```

**Comment by langner** [comment]
I'm OK with moving to the second directory structure with less nesting. I don't see any drawbacks.
