### ISSUE TITLE
Error Attempting to Parse NWChem 6.8

### ISSUE THREAD

**Issue by nkl311** [cclib/cclib#526]
Hi, thanks for maintaining this great tool.

I'm very new at this, so I may be making a basic error. I'm trying to parse MO coefficients from NWChem 6.8 output file using
```
ccget mocoeffs nm.output.2113838
```
and I'm getting the error
```
Attempting to read nm.output.2113838
Traceback (most recent call last):
  File "C:/ProgramData/Miniconda3/Scripts/ccget", line 198, in <module>
    ccget()
  File "C:/ProgramData/Miniconda3/Scripts/ccget", line 161, in ccget
    data = ccread(filename, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\cclib\io\ccio.py", line 121, in ccread
    return log.parse()
  File "C:\ProgramData\Miniconda3\lib\site-packages\cclib\parser\logfileparser.py", line 301, in parse
    self.extract(inputfile, line)
  File "C:\ProgramData\Miniconda3\lib\site-packages\cclib\parser\nwchemparser.py", line 338, in extract
    self.scftargets.append(self.scftargets[-1])
AttributeError: 'NWChem' object has no attribute 'scftargets'
```
I've also tried several other attributes such as ```natoms``` and ```nbasis``` and get the same error.

Any help would be appreciated.

[nw_run.zip](https://github.com/cclib/cclib/files/2055156/nw_run.zip)

**Comment by berquist** [comment]
Thank you for the report. The problem stems from the use of `print low` in the input: it suppresses all information about SCF settings (targets) and iterations, which the parser currently expects. A fix is to not require the presence of those in some cases.

However, looking at the output file, not even the MO coefficients are present, so you'd get an `AttributeError` if we didn't get this printing problem. The coefficients are available in the Molden file, but we currently don't have a reader for it. I have used the one in [orbkit](https://github.com/orbkit/orbkit) successfully.

In order to get the MO coefficients directly in the output file, add the following line to your `dft` block:
```
print "final vectors" "final vectors analysis"
```
You may also need to remove `print low` depending on what other attributes you need.

**Comment by langner** [comment]
@berquist  is right - we can't parse things that are not there.

We should add the file as a regression, though, so that at least we don't fail. Eric, were you planning on doing that? If not, I will.

**Comment by berquist** [comment]
Yes, I will fix it.

**Comment by nkl311** [comment]
Thanks for the helpful discussion! I will let you know if I run into more problems, but right now it looks like I have a clear path ahead.
