### ISSUE TITLE
Scripts don't work outside of source tree when developing

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#527]
Ever since our discussion in https://github.com/cclib/cclib/issues/459 and the rewrite of `setup.py`, I've been getting the following traceback any time I try and run `ccget` outside of the development directory:
```
/home/eric/Dropbox/research/cclib/526  (env: cclib_berquist 3.6.5)
[eric@osmium]$ ccget --verbose --list nm.output.2113838
Traceback (most recent call last):
  File "/home/eric/data/virtualenvs/3/cclib_berquist/bin/ccget", line 11, in <module>
    load_entry_point('cclib', 'console_scripts', 'ccget')()
  File "/home/eric/data/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point                                                                                                                                     
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/eric/data/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point                                                                                                                                    
    return ep.load()
  File "/home/eric/data/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/home/eric/data/virtualenvs/3/cclib_berquist/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'cclib.scripts'
/home/eric/Dropbox/research/cclib/526  (env: cclib_berquist 3.6.5)
[eric@osmium]$ echo $VIRTUAL_ENV
/home/eric/data/virtualenvs/3/cclib_berquist
/home/eric/Dropbox/research/cclib/526  (env: cclib_berquist 3.6.5)
[eric@osmium]$ which ccget
/home/eric/data/virtualenvs/3/cclib_berquist/bin/ccget
/home/eric/Dropbox/research/cclib/526  (env: cclib_berquist 3.6.5)
[eric@osmium]$ pip list
Package        Version Location                                   
-------------- ------- -------------------------------------------
atomicwrites   1.1.5   
attrs          18.1.0  
berny          0.1     
biopython      1.71    
cclib          1.5.3   /home/eric/development/cclib_berquist/cclib
coverage       4.5.1   
mmd            0.0.1   
more-itertools 4.2.0   
numpy          1.14.3  
openbabel      2.4.1   
pip            10.0.1  
pluggy         0.6.0   
py             1.5.3   
pyparsing      2.2.0   
pytest         3.6.0   
pytest-cov     2.5.1   
setuptools     39.2.0  
six            1.11.0  
```
I've installed using `pip install -e .`, and my virtual environment was created in the current standard way (I think): `python -m venv ~/data/virtualenvs/3/cclib_berquist`.

**Comment by langner** [comment]
Yeah, me to, actually, also I've never noticed since I don't often run the scripts from a virtualenv. Here's my workflow, a bit different than yours:
```
kml@subito:~$ source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
kml@subito:~$ cd tmp/cclib.gi
(cclib2) kml@subito:~/tmp/cclib.git$ python setup.py install -f
running install
...
(cclib2) kml@subto:~/tmp/cclib.git$ ccget --list data/NWChem/basicNWChem6.0/C_bigbasis.out 
Traceback (most recent call last):
  File "/home/kml/.virtualenvs/cclib2/bin/ccget", line 11, in <module>
    load_entry_point('cclib==1.5.3', 'console_scripts', 'ccget')()
  File "/home/kml/.virtualenvs/cclib2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/kml/.virtualenvs/cclib2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/home/kml/.virtualenvs/cclib2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/kml/.virtualenvs/cclib2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named cclib.scripts.ccget
```

**Comment by berquist** [comment]
This is essentially the same thing; now that I have a new machine I should probably stop doing virtualenv stuff by hand.

I also have a file conflict with the `progress` directory trying to install another system package; I have a copy in `/usr` for when I need to actually use cclib. I wonder if it's related, since these are all popping up after the directory reorganization. I can't use cclib outside of the source tree at all:

```
/home/eric  (env: cclib_berquist 3.6.5)
[eric@gold]$ python -c 'import cclib'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
```

**Comment by berquist** [comment]
That was easier than I thought:
```diff
diff --git a/setup.py b/setup.py
index a170c2f3..db7b57d0 100755
--- a/setup.py
+++ b/setup.py
@@ -47,8 +47,7 @@ def setup_cclib():
         long_description="\n".join(doclines[2:]),
         classifiers=classifiers.split("\n"),
         platforms=["Any."],
-        packages=setuptools.find_packages('cclib'),
-        package_dir={'': 'cclib'},
+        packages=setuptools.find_packages(exclude=['tests']),
         entry_points={
             'console_scripts': [
                 'ccget=cclib.scripts.ccget:ccget',
```
