### ISSUE TITLE
orcaparser.py: "ValueError: not enough values to unpack (expected 4, got 1)"

### ISSUE THREAD

**Issue by dudektria** [cclib/cclib#650]
Hi, it's me again :)

Both of the following inputs run fine in ORCA:

```
% cat h2.inp 
! Opt

*xyz 0 1
H 0.0 0.0 0.0
H 1.0 0.0 0.0
end
%pal
 nprocs 1
end
```
```
% cat h2_other.inp 
! Opt

*xyz 0 1
H 0.0 0.0 0.0
H 1.0 0.0 0.0
*
%pal
 nprocs 1
end
```

The only difference is how the coordinates block ends: the first with `end`, the second with `*`. Even though `*` is shown in the ORCA manual, **both inputs work** ([inputs and outputs are attached][ins-and-outs.zip]) and finish with the same energy.

In fact, both calculations are essentially **identical**:

```
% grep "FINAL SINGLE POINT ENERGY" *out
h2_other.out:FINAL SINGLE POINT ENERGY        -1.100088862913
h2_other.out:FINAL SINGLE POINT ENERGY        -1.123630637764
h2_other.out:FINAL SINGLE POINT ENERGY        -1.125509217942
h2_other.out:FINAL SINGLE POINT ENERGY        -1.128725333376
h2_other.out:FINAL SINGLE POINT ENERGY        -1.128920981694
h2_other.out:FINAL SINGLE POINT ENERGY        -1.128928546128
h2_other.out:FINAL SINGLE POINT ENERGY        -1.128928568092
h2.out:FINAL SINGLE POINT ENERGY        -1.100088862913
h2.out:FINAL SINGLE POINT ENERGY        -1.123630637764
h2.out:FINAL SINGLE POINT ENERGY        -1.125509217942
h2.out:FINAL SINGLE POINT ENERGY        -1.128725333376
h2.out:FINAL SINGLE POINT ENERGY        -1.128920981694
h2.out:FINAL SINGLE POINT ENERGY        -1.128928546128
h2.out:FINAL SINGLE POINT ENERGY        -1.128928568092
```

But while `ccget` reads one fine, it can't read the other:

```
% ccget scfenergies h2_other.out h2.out 
Attempting to read h2_other.out
scfenergies
[-29.93494156 -30.575546   -30.62666476 -30.71417957 -30.71950348
 -30.71970947 -30.71971001]
Attempting to read h2.out
Traceback (most recent call last):
  File "/usr/local/bin/ccget", line 11, in <module>
    load_entry_point('cclib', 'console_scripts', 'ccget')()
  File "/home/schneider/Dropbox/cclib/cclib/scripts/ccget.py", line 165, in ccget
    data = ccread(filename, **kwargs)
  File "/home/schneider/Dropbox/cclib/cclib/io/ccio.py", line 175, in ccread
    return log.parse()
  File "/home/schneider/Dropbox/cclib/cclib/parser/logfileparser.py", line 318, in parse
    self.extract(inputfile, line)
  File "/home/schneider/Dropbox/cclib/cclib/parser/orcaparser.py", line 176, in extract
    coords.append(splitter(line))
  File "/home/schneider/Dropbox/cclib/cclib/parser/orcaparser.py", line 144, in splitter
    atom, x, y, z = line.split()[:4]
ValueError: not enough values to unpack (expected 4, got 1)
```

[ins-and-outs.zip]: https://github.com/cclib/cclib/files/2568757/ins-and-outs.zip

**Comment by berquist** [comment]
Ugh, invalid inputs that actually run...

Can you make a regression PR? I'll do the code fix.
