### ISSUE TITLE
pytest is not catching failing tests

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#739]
These failures appear with `python -m test.test_data --terse`:
```
********* SUMMARY OF FAILURES *********

basicORCA4.1/dvb_rocis.out: Customized test for ROCIS
testTransprop (test.data.testTD.OrcaROCISTest)Traceback (most recent call last):
  File "/home/eric/development/cclib_berquist/test/data/testTD.py", line 172, in testTransprop
    self.assertEqual(len(self.data.transprop), self.n_spectra)
AssertionError: 8 != 9

basicORCA4.1/dvb_rocis.out: Customized test for ROCIS
testenergies (test.data.testTD.OrcaROCISTest)Traceback (most recent call last):
  File "/home/eric/development/cclib_berquist/test/data/skip.py", line 18, in testwrapper
    testfunc(self, *args, **kwargs)
  File "/home/eric/development/cclib_berquist/test/data/skip.py", line 18, in testwrapper
    testfunc(self, *args, **kwargs)
  File "/home/eric/development/cclib_berquist/test/data/testTD.py", line 37, in testenergies
    self.assertAlmostEqual(self.data.etenergies[idx_lambdamax], self.expected_l_max, delta=5000)
AssertionError: 1.0 != 2316970.8 within 5000 delta
```
but not with `python -m pytest -v --capture=no test/test_data.py`. Putting a print statement into `testTransprop` shows that the test is only being run once, even though it's specified twice:
```
TD        ORCA        OrcaROCISTest         basicORCA4.0          dvb_rocis.out
TD        ORCA        OrcaROCISTest         basicORCA4.1          dvb_rocis.out
```

**Comment by berquist** [comment]
`silent=True` is swallowing errors https://github.com/cclib/cclib/blob/5605bdd98085a7e41dee4965bf0573aeefe89b2e/test/test_data.py#L272

**Comment by berquist** [comment]
It happens because a non-zero exit code is only returned when the summary is printed, and that method is only called when `silent` is false.

**Comment by berquist** [comment]
This was fixed by a combination of https://github.com/cclib/cclib/pull/675, https://github.com/cclib/cclib/pull/743, and https://github.com/cclib/cclib/pull/744.
