### ISSUE TITLE
ORCA excited state optimization logfiles sometimes raise AttributeError: 'numpy.ndarray' object has no attribute 'append'

### ISSUE THREAD

**Issue by schneiderfelipe** [cclib/cclib#740]
I just found a strange error with an excited state optimization when calling `ccobj.parse()`:

```
[ORCA last/porphine.out INFO] Creating attribute metadata: {}
[ORCA last/porphine.out INFO] Creating attribute charge: 0
[ORCA last/porphine.out INFO] Creating attribute geotargets[]
[ORCA last/porphine.out INFO] Creating attribute natom: 38
[ORCA last/porphine.out INFO] Creating attribute atomnos[]
[ORCA last/porphine.out INFO] Creating attribute atomcoords[]
[ORCA last/porphine.out INFO] Creating attribute atommasses[]
[ORCA last/porphine.out INFO] Creating attribute gbasis[]
[ORCA last/porphine.out INFO] Creating attribute nbasis: 498
[ORCA last/porphine.out INFO] Creating attribute mult: 1
[ORCA last/porphine.out INFO] Creating attribute scfvalues[]
[ORCA last/porphine.out INFO] Creating attribute scfenergies[]
[ORCA last/porphine.out INFO] Creating attribute scftargets[]
[ORCA last/porphine.out INFO] Creating attribute moenergies[]
[ORCA last/porphine.out INFO] Creating attribute homos[]
[ORCA last/porphine.out INFO] Creating attribute aonames[]
[ORCA last/porphine.out INFO] Creating attribute atombasis[]
[ORCA last/porphine.out INFO] Creating attribute mocoeffs[]
[ORCA last/porphine.out INFO] Creating attribute atomcharges: {}
[ORCA last/porphine.out INFO] Creating attribute etsecs[]
[ORCA last/porphine.out INFO] Creating attribute etenergies[]
[ORCA last/porphine.out INFO] Creating attribute etsyms[]
[ORCA last/porphine.out INFO] Creating attribute transprop: {}
[ORCA last/porphine.out INFO] Creating attribute etoscs[]
[ORCA last/porphine.out INFO] Creating attribute etrotats[]
[ORCA last/porphine.out INFO] Creating attribute grads[]
[ORCA last/porphine.out INFO] Creating attribute geovalues[]
Traceback (most recent call last):
  File "/usr/local/bin/noivibs", line 11, in <module>
    load_entry_point('pyrrole', 'console_scripts', 'noivibs')()
  File "/mnt/Files/Dropbox/Dropbox/pyrrole/pyrrole/scripts/noivibs.py", line 30, in cli
    mol = read_cclib(path)
  File "/mnt/Files/Dropbox/Dropbox/pyrrole/pyrrole/atoms.py", line 1765, in read_cclib
    ccdata = ccobj.parse()
  File "/mnt/Files/Dropbox/Dropbox/cclib/cclib/parser/logfileparser.py", line 329, in parse
    self.extract(inputfile, line)
  File "/mnt/Files/Dropbox/Dropbox/cclib/cclib/parser/orcaparser.py", line 776, in extract
    self.etenergies.append(float(broken[-2]))
AttributeError: 'numpy.ndarray' object has no attribute 'append'
```

The logfile is attached ([logfile.zip](https://github.com/cclib/cclib/files/3209612/logfile.zip)). Any clues?

**Comment by langner** [comment]
Confirmed on master.

**Comment by langner** [comment]
It seems this file has both the `TD-DFT/TDA EXCITED` and `ABSORPTION SPECTRUM` blocks, the latter of which set `etenergies` to a NumPy array. When the former tried to add directly to `etenergies`, that's where the error comes up. What kind of behavior would you expect in this case?

This file also has the `CD SPECTRUM` block... which actually doesn't set `etenergies` if it is already set. Is that also expected?

**Comment by schneiderfelipe** [comment]
I don't know about the  `CD SPECTRUM` block, but this is an excited-state optimization, so `TD-DFT/TDA EXCITED` and `ORCA SCF GRADIENT CALCULATION` blocks are going back and forth. I would expect intermediate energies to reflect those excited-state calculations if they are to be kept.

On the other hand, the `etenergies` that really mean something are the last ones. Maybe setting it to a NumPy array only at the end? I'm not sure.

**Comment by langner** [comment]
In that case #741 should help.

**Comment by berquist** [comment]
Based on the comments, I'd say this was closed by https://github.com/cclib/cclib/pull/741.
