### ISSUE TITLE
Developer documentation is missing information for local testing

### ISSUE THREAD

**Issue by ATenderholt** [cclib/cclib#946]
Only relevant documentation states:
> When adding new features and tests, the Travis CI testing script can be run locally to generate the HTML coverage pages and ensure that the tests exercise the feature code.

How does one run a single test? This is what I get running a single script:

```
$ python test/test_data.py 
Couldn't find cython becke routine
Traceback (most recent call last):
  File "test/test_data.py", line 46, in <module>
    for tn in module_names}
  File "test/test_data.py", line 46, in <dictcomp>
    for tn in module_names}
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'test.data.testSP'
```

**Comment by berquist** [comment]
I think you have to run them as modules, not loose files. For example, to run the ORCA TDDFT tests the old way,
```bash
python -m test.test_data --terse ORCA TD
```
but I don't know how to narrow it down further. The way tests are read from `testdata` right now also means that we can't use pytest to automatically discover individual unit tests for the parsers, only for IO, bridges, etc.
