### ISSUE TITLE
Error when reading Orca optimization with constraints

### ISSUE THREAD

**Issue by jevandezande** [cclib/cclib#947]
When cclib attempts to read an orca 4.2.1 output file with constraints, it gives the following error:
```
[ORCA output.txt ERROR] Encountered error when parsing.
[ORCA output.txt ERROR] Last line read: WARNING: THERE ARE 5 CONSTRAINED CARTESIAN COORDINATES

Traceback (most recent call last):File "<stdin>", line 1, in <module>
    File "/home/orca/.local/lib/python3.7/site-packages/cclib/io/ccio.py", line 182, in ccread
        return log.parse()
    File "/home/orca/.local/lib/python3.7/site-packages/cclib/parser/logfileparser.py", line 335, in parse
        self.extract(inputfile, line)
    File "/home/orca/.local/lib/python3.7/site-packages/cclib/parser/orcaparser.py", line 476, in extract
        x, y, z = float(tokens[-3]), float(tokens[-2]), float(tokens[-1])
ValueError: could not convert string to float: 'CONSTRAINED'
```

Minimal example input attached and reproduced below:

```
! Opt HF-3C
% geom
    Constraints
        {C 0 C}
    end
end

* xyz 0 1
    H   0   0   0
    H   0   0   1
*         
```

[input.txt](https://github.com/cclib/cclib/files/5233940/input.txt)
[output.txt](https://github.com/cclib/cclib/files/5233942/output.txt)

**Comment by berquist** [comment]
Thanks Jonathon. Do you have a fix, or should one of us work on it?

**Comment by jevandezande** [comment]
I won't have time to submit a fix on this for a while, so it would be best if someone else could look into it.
