### ISSUE TITLE
fail to create xyz with ccwrite 

### ISSUE THREAD

**Issue by mit-eremin** [cclib/cclib#986]
When using terminal to create xyz file I get this error:
```
Traceback (most recent call last):
  File "/Users/eremin/anaconda3/bin/ccwrite", line 10, in <module>
    sys.exit(main())
  File "/Users/eremin/anaconda3/lib/python3.7/site-packages/cclib/scripts/ccwrite.py", line 105, in main
    **ccwrite_kwargs)
  File "/Users/eremin/anaconda3/lib/python3.7/site-packages/cclib/io/ccio.py", line 381, in ccwrite
    output = outputobj.generate_repr()
  File "/Users/eremin/anaconda3/lib/python3.7/site-packages/cclib/io/xyzwriter.py", line 73, in generate_repr
    xyzblock.append(self._xyz_from_ccdata(i))
  File "/Users/eremin/anaconda3/lib/python3.7/site-packages/cclib/io/xyzwriter.py", line 84, in _xyz_from_ccdata
    existing_comment = "" if not self.ccdata.metadata["comments"] \
KeyError: 'comments'
```
It works for cml format with no problem.
Using macOS 10.15.7 on MacBook Pro.

**Comment by berquist** [comment]
This is the same problem as #814 and will be fixed by #815. I'll fix this ASAP.
