### ISSUE TITLE
Psi4 SAPT0 calculation that doesn't parse

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#993]
It's unclear where in the parser this is happening:
```
$ ccget scfenergies mg_ct_sapt_gas.out
Attempting to read mg_ct_sapt_gas.out
TypeError: float() argument must be a string or a number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eric/.pyenv/versions/miniconda3-4.7.12/envs/cclib_berquist_37/bin/ccget", line 33, in <module>
    sys.exit(load_entry_point('cclib', 'console_scripts', 'ccget')())
  File "/home/eric/development/cclib_berquist/cclib/scripts/ccget.py", line 171, in ccget
    data = ccread(filename, **kwargs)
  File "/home/eric/development/cclib_berquist/cclib/io/ccio.py", line 182, in ccread
    return log.parse()
  File "/home/eric/development/cclib_berquist/cclib/parser/logfileparser.py", line 366, in parse
    data = self.datatype(attributes=self.__dict__)
  File "/home/eric/development/cclib_berquist/cclib/parser/data.py", line 413, in __init__
    super(ccData_optdone_bool, self).__init__(*args, **kwargs)
  File "/home/eric/development/cclib_berquist/cclib/parser/data.py", line 204, in __init__
    self.setattributes(attributes)
  File "/home/eric/development/cclib_berquist/cclib/parser/data.py", line 417, in setattributes
    invalid = super(ccData_optdone_bool, self).setattributes(*args, **kwargs)
  File "/home/eric/development/cclib_berquist/cclib/parser/data.py", line 275, in setattributes
    self.arrayify()
  File "/home/eric/development/cclib_berquist/cclib/parser/data.py", line 231, in arrayify
    setattr(self, k, numpy.array(getattr(self, k), precision))
ValueError: setting an array element with a sequence.
```

**Comment by berquist** [comment]
The problem is that the different fragment calculations that are a part of a SAPT0-CT calculation (or would be present in any SAPT calculation that has steps in the monomer basis) have geometry blocks with fewer atoms than in the supersystem. In dimer basis steps, missing atoms still have ghost centers, but monomer basis steps have the other fragment completely missing. (This is almost certainly a problem with parsing Q-Chem fragment calculations too, but I must not have tried doing so with the right output yet.)

The proper solution would involve treating each fragment calculation as an individual `ccData` objects (#131), but then in the future when you want to parse the actual SAPT or ALMO-EDA quantities of interest, those would depend on the combination of `ccData` objects.

In the meantime, a possible solution to get the file parsing is to recognize a SAPT calculation and toss all but the supersystem (combined input) geometry, leaving the separate individual SCF energies, and it would be up to the user to know which energies correspond to which step.
